const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const GENRES=['Trending music','Bollywood hits','Punjabi songs','Romantic Hindi songs','Lo-fi chill music','Workout music','90s Hindi songs'];
const PLAYLISTS=[['Today’s Top Hits','today top music hits'],['Bollywood Hits','latest bollywood songs'],['Punjabi Party','popular punjabi songs'],['Romantic Vibes','romantic hindi songs'],['Lo-Fi & Chill','lofi chill music']];
let ytReady=false,yt,current=null,queue=[],idx=-1,last=[],timer,repeat=false;
let fav=JSON.parse(localStorage.ob5fav||'[]'),recent=JSON.parse(localStorage.ob5recent||'[]'),history=JSON.parse(localStorage.ob5history||'[]');
window.onYouTubeIframeAPIReady=()=>ytReady=true;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function save(){localStorage.ob5fav=JSON.stringify(fav);localStorage.ob5recent=JSON.stringify(recent);localStorage.ob5history=JSON.stringify(history)}
async function api(q){const r=await fetch('/api/search?q='+encodeURIComponent(q));const d=await r.json();if(!r.ok)throw Error(d.error||'Search failed');return d}
function songCard(x,i){return `<article class="song" data-i="${i}"><div class="cover"><img loading="lazy" src="${x.thumbnail}" alt=""><button class="play">▶</button><button class="add">＋</button></div><b>${esc(x.title)}</b><span>${esc(x.channel)}</span></article>`}
function renderSongs(el,items){el.innerHTML=items?.length?items.map(songCard).join(''):'<p class="empty">Nothing here yet.</p>';[...el.querySelectorAll('.song')].forEach((e,i)=>e.onclick=ev=>{const x=items[i];if(ev.target.closest('.add')){queue.push(x);renderQueue();toast('Added to queue')}else{if(!queue.length)queue=[...items];idx=queue.findIndex(y=>y.id===x.id);play(x)}})}
function renderQueue(){ $('#queueCount').textContent=queue.length;$('#queueList').innerHTML=queue.length?queue.slice(0,10).map((x,i)=>`<div class="queue-item"><img src="${x.thumbnail}" alt=""><div><b>${i===idx?'▶ ':''}${esc(x.title)}</b><span>${esc(x.channel)}</span></div></div>`).join(''):'<p class="empty">Your queue is empty.</p>'}
function renderPlaylists(){$('#playlistGrid').innerHTML=PLAYLISTS.map((p,i)=>`<button class="playlist" data-i="${i}">${p[0]}<small>Tap to play</small></button>`).join('');$$('.playlist').forEach(e=>e.onclick=()=>loadQuery(PLAYLISTS[+e.dataset.i][1],PLAYLISTS[+e.dataset.i][0],true));$('#sideGenres').innerHTML=GENRES.map(g=>`<button class="genre" data-q="${g}">♪ ${g}</button>`).join('');$$('.genre').forEach(e=>e.onclick=()=>loadQuery(e.dataset.q,e.dataset.q,true))}
function renderArtists(items){const a=[];items.forEach(x=>{if(!a.some(y=>y.channel===x.channel))a.push(x)});$('#artistGrid').innerHTML=a.slice(0,8).map(x=>`<div class="artist"><img loading="lazy" src="${x.thumbnail}" alt=""><b>${esc(x.channel)}</b></div>`).join('')}
function play(v){current=v;if(idx<0){queue.push(v);idx=queue.length-1}['nowTitle','miniTitle'].forEach(id=>$('#'+id).textContent=v.title);['nowArtist','miniArtist'].forEach(id=>$('#'+id).textContent=v.channel);['bigThumb','miniThumb'].forEach(id=>$('#'+id).src=v.thumbnail);recent=[v,...recent.filter(x=>x.id!==v.id)].slice(0,40);save();setLike();if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:v.title,artist:v.channel,artwork:[{src:v.thumbnail,sizes:'512x512',type:'image/jpeg'}]});navigator.mediaSession.setActionHandler('nexttrack',next);navigator.mediaSession.setActionHandler('previoustrack',prev)}const go=()=>{if(yt?.loadVideoById){yt.loadVideoById(v.id);yt.playVideo()}else yt=new YT.Player('youtubePlayer',{videoId:v.id,playerVars:{autoplay:1,rel:0,playsinline:1},events:{onReady:e=>e.target.playVideo(),onStateChange:e=>{if(e.data===0){repeat?play(current):next()}}})};if(ytReady)go();else setTimeout(go,400)}
function next(){if(!queue.length)return;idx=(idx+1)%queue.length;play(queue[idx])}function prev(){if(!queue.length)return;idx=(idx-1+queue.length)%queue.length;play(queue[idx])}
function toggle(){if(!yt)return;yt.getPlayerState?.()===1?yt.pauseVideo():yt.playVideo()}function setLike(){const yes=current&&fav.some(x=>x.id===current.id);$('#likeBtn').textContent=yes?'♥':'♡';$('#miniLike').textContent=yes?'♥':'♡'}
function like(){if(!current)return;const i=fav.findIndex(x=>x.id===current.id);i>=0?fav.splice(i,1):fav.unshift(current);save();setLike()}
function view(v){['home','search','library','recent'].forEach(x=>$('#'+x+'View').classList.toggle('hidden',x!==v));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.view===v));if(v==='library')renderSongs($('#libraryGrid'),fav);if(v==='recent')renderSongs($('#recentGrid'),recent);if(v==='search')renderHistory()}
function renderHistory(){const el=$('#suggestions');el.className='history';el.innerHTML=history.length?history.map(x=>`<button data-h="${esc(x)}">⌕ ${esc(x)}</button>`).join(''):'';el.querySelectorAll('button').forEach(e=>e.onclick=()=>doSearch(e.dataset.h))}
async function loadQuery(q,title,home=false){if(home){$('#trendingTitle').textContent=title;view('home')}try{const d=await api(q);last=d.items;renderSongs(home?$('#trendingGrid'):$('#searchGrid'),d.items);queue=d.items;idx=-1;renderQueue();if(home)renderArtists(d.items)}catch(e){toast(e.message)}}
async function doSearch(q){q=q.trim();if(q.length<3)return;history=[q,...history.filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,12);save();view('search');$('#searchTitle').textContent=`Results for “${q}”`;$('#searchStatus').textContent='Searching…';try{const d=await api(q);last=d.items;renderSongs($('#searchGrid'),d.items);$('#searchStatus').textContent=`${d.items.length} results${d.cached?' • cached':''}`}catch(e){$('#searchGrid').innerHTML=`<p class="empty">${esc(e.message)}</p>`;$('#searchStatus').textContent='Unavailable'}}
$('#searchForm').onsubmit=e=>{e.preventDefault();doSearch($('#searchInput').value)};$('#searchInput').oninput=()=>{clearTimeout(timer);const q=$('#searchInput').value.trim();if(q.length>=3)timer=setTimeout(()=>doSearch(q),650)};$$('.nav').forEach(e=>e.onclick=()=>view(e.dataset.view));$('#clearHistory').onclick=()=>{history=[];save();renderHistory()};$('#newPlaylist').onclick=()=>toast('Custom playlist creation is stored locally in the next update');$('#heroPlay').onclick=()=>last[0]?play(last[0]):loadQuery('popular music','Trending now',true);$$('.see').forEach(e=>e.onclick=()=>loadQuery(e.dataset.query,'Trending now',true));
['playBtn','bottomPlay'].forEach(id=>$('#'+id).onclick=toggle);['prevBtn','bottomPrev'].forEach(id=>$('#'+id).onclick=prev);['nextBtn','bottomNext'].forEach(id=>$('#'+id).onclick=next);['shuffleBtn','bottomShuffle'].forEach(id=>$('#'+id).onclick=()=>{queue.sort(()=>Math.random()-.5);idx=queue.findIndex(x=>x.id===current?.id);renderQueue();toast('Queue shuffled')});['repeatBtn','bottomRepeat'].forEach(id=>$('#'+id).onclick=()=>{repeat=!repeat;toast(repeat?'Repeat one enabled':'Repeat disabled')});$('#likeBtn').onclick=like;$('#miniLike').onclick=like;$('#clearQueue').onclick=()=>{queue=[];idx=-1;renderQueue()};$('#panelBtn').onclick=()=>document.body.classList.toggle('right-open');$('#closePanel').onclick=()=>document.body.classList.remove('right-open');$('#videoBtn').onclick=()=>current?$('#videoModal').classList.remove('hidden'):toast('Choose a song first');$('#closeVideo').onclick=()=>$('#videoModal').classList.add('hidden');$('#volume').oninput=e=>yt?.setVolume(+e.target.value);$('#muteBtn').onclick=()=>yt&&(yt.isMuted()?yt.unMute():yt.mute());$('#menuBtn').onclick=()=>document.body.classList.toggle('side-open');$('#mobileSearch').onclick=()=>{view('search');$('#searchInput').focus()};$('#themeBtn').onclick=()=>toast('Dark premium theme active');let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').style.display='block'});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else toast('Use your browser menu → Install app')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
renderPlaylists();loadQuery('popular music','Trending now',true);